### ISSUE TITLE
JFeatureLib dependencies not found on Maven Repo

### ISSUE THREAD

**Issue by judahk** [locked-fg/JFeatureLib#25]
I am using JFeatureLib library which I include in my project through Maven. However, my maven build is breaking because Maven cannot download two of the dependencies needed by JFeatureLib: imageanalysis and lire. Can you please fix this so that Maven can automatically download libraries needed by JFeatureLib to function properly. 

Here is the link to Maven repo: http://mvnrepository.com/artifact/de.lmu.ifi.dbs.jfeaturelib/JFeatureLib/1.6.0

Thanks,
Kshitij Judah

**Comment by locked-fg** [comment]
Explained how to get LIRE in https://github.com/locked-fg/JFeatureLib/wiki/DevelopmentFAQ#lire
