### ISSUE TITLE
Haralick feature should be wrong.

### ISSUE THREAD

**Issue by babysor** [locked-fg/JFeatureLib#26]
The third one, Correlation, of Haralick features shouldn't higher than 1, but in the result of your code. It will be unreasonably high. I'm trying to debug, any idea about it?

**Comment by babysor** [comment]
First of all, the meanGrayValue calculation is wrong. Even though modified in 1.5.1, the right value should be meanGrayValue = graySum / size/ GRAY_SCALE; instead of meanGrayValue = graySum / size/ GRAY_SCALE.

**Comment by babysor** [comment]
Plus, the calculation of cooccurent also has some issues.In your 4 directions (0,90,45,135), the 45 and 135 are doing the duplicate thing after the iteration of whole matrix.

**Comment by locked-fg** [comment]
Thanks for the hint. the meanGrayValue calc was indeed wrong. Yet I wonder, what the more reasonable result would be:
An image quantized into 8 steps (equals: Haralick.Coocurrence(ip, 8, something) = 32 step size), the mean Gray Value for pixels in the range 0-31 should be 0, but should 32-63 be 2 or 32?
Both would be valid. In the one case the resulting image has only values 0-7, in the other it has values 0-224.

**Comment by locked-fg** [comment]
Closing dueto lack of response. There doesn't seem to be a one and only correct point of view.
