### ISSUE TITLE
Banned dependencies

### ISSUE THREAD

**Issue by lmiroslaw** [locked-fg/JFeatureLib#27]
I cannot build my project that uses JFeatureLib due to following error:

[WARNING] Rule 6: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: de.lmu.ifi.dbs.utilities:common-extension-lib:jar:2.4.0
Found Banned Dependency: de.lmu.ifi.dbs.jfeaturelib:JFeatureLib:jar:1.6.1
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ----------------
Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-rules) on project : 
Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.

I tried to use mvn install -Denforcer.skip=true but it did not work as well (Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin).I tried to use mvn install -Denforcer.skip=true but it did not work as well (Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin).

**Comment by locked-fg** [comment]
Hm I can't reproduce that.

git clone https://github.com/locked-fg/JFeatureLib.git
git clone https://github.com/locked-fg/LIRE.git
cd LIRE 
mvn install -Dmaven.test.skip=true

cd ../JFeatureLib
mvn compile 

all this works pretty smooth. What exactly are you doing?

**Comment by lmiroslaw** [comment]
Hi Franz,

I have a mvn project where I want to calculate Haralick features with
JFeatureLib.
In search.maven.org I found the following entry I imported it to my
project. Since I did not need LIRE I excluded it from the compilation.

<dependency>
            <groupId>de.lmu.ifi.dbs.jfeaturelib</groupId>
            <artifactId>JFeatureLib</artifactId>
            <version>1.6.1</version>
            <exclusions>
                <exclusion>
                    <groupId>net.semanticmetadata</groupId>
                    <artifactId>lire</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

Have you managed to mvn clean install a project like this?

Thanks,
Lukasz



On Sun, Aug 23, 2015 at 1:31 PM, Franz Graf <notifications@github.com>
wrote:

> Hm I can't reproduce that.
>
> git clone https://github.com/locked-fg/JFeatureLib.git
> git clone https://github.com/locked-fg/LIRE.git
> cd LIRE
> mvn install -Dmaven.test.skip=true
>
> cd ../JFeatureLib
> mvn compile
>
> all this works pretty smooth. What exactly are you doing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locked-fg/JFeatureLib/issues/27#issuecomment-133819581>
> .
>



-- 
Łukasz Mirosław, Ph.D.
Senior Research Associate
Institute of Informatics
Wrocław University of Technology
Wyb. Wyspiańskiego 27
PL50370 Wrocław, Poland

Email: lukasz.miroslaw@pwr.wroc.pl
Tel.: +48713203969
Web: www.ii.pwr.wroc.pl/~miroslaw <http://www.ii.pwr.wroc.pl/%7Emiroslaw>

**Comment by locked-fg** [comment]
Hi Lukasz, 

Sorry never tried anything like that with Jfeaturelib. 
Is it really a Jfeaturelib bug? 
Sounds more like a Maven thing. 

Cheers Franz

**Comment by lmiroslaw** [comment]
Hi Franz,

I am preaty sure there are banned dependencies in JFeaturelib maven files
or JFeaturelib dependencies.
That's why I cannot build it.

Have you tried to create a project and download your library from maven and
call any function from the project? That's a standard scenario for those
who want to use JFeature externally. We will immediately see if this is a
maven configuration problem or not.

Best wishes,
Lukasz

**Comment by locked-fg** [comment]
Hi Lukasz,

you mean like in the Demo project?
https://github.com/locked-fg/JFeatureLib-Demo
Or do you think of something different?

Cheers
Franz

**Comment by lmiroslaw** [comment]
Thanks for the link.

I see one big difference now. In the demo project you use version 1.6.2
from your repository.
I used version 1.6.1 from maven public repository (see search.maven.com ->
JFeatureLib) as this is the newest available there.
You might want to update it at some point in future.

That could be the reason why I have a problem.

Cheers,
Lukasz

**Comment by locked-fg** [comment]
Hey Lukasz,

the maven repo usually takes a day or to to get the latest snapshots. (They're there now.)

I just tried the following:

rm -rf ~/.m2
cd temp

rm -rf LIRE
git clone https://github.com/locked-fg/LIRE.git
cd LIRE
mvn install -Dmaven.test.skip=true

cd ..
rm -rf JFeatureLib-Demo
git clone https://github.com/locked-fg/JFeatureLib-Demo.git
cd JFeatureLib-Demo
mvn compile 

All that works like a charm.
Anything else I should check?

Cheers Franz

**Comment by lmiroslaw** [comment]
That's true. Thanks!

I can see the version 1.6.2 now and will test it soon.

Thank you Franz,
Lukasz

**Comment by locked-fg** [comment]
Hey Lukasz,

anything new in this issue?

Regards
Franz

**Comment by locked-fg** [comment]
I assume everything to be working

**Comment by lmiroslaw** [comment]
Hi Franz,

I believe so as well although had no time to test it yet because I got sick.

Best,
Lukasz

On Fri, Sep 11, 2015 at 8:45 PM, Franz Graf <notifications@github.com>
wrote:

> I assume everything to be working
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locked-fg/JFeatureLib/issues/27#issuecomment-139624380>
> .
>



-- 
Łukasz Mirosław, Ph.D.
Senior Research Associate
Institute of Informatics
Wrocław University of Technology
Wyb. Wyspiańskiego 27
PL50370 Wrocław, Poland

Email: lukasz.miroslaw@pwr.wroc.pl
Tel.: +48713203969
Web: www.ii.pwr.wroc.pl/~miroslaw <http://www.ii.pwr.wroc.pl/%7Emiroslaw>

**Comment by locked-fg** [comment]
heyo,

feel free to reopen if you think it's a bug.
​And man, get well soon!

Franz
