### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by cute-jumper** [locked-fg/JFeatureLib#32]
The master branch can't be compiled successfully. The error is cause by https://github.com/locked-fg/JFeatureLib/blob/cf815a02c4376ce5e68f4862150c52e3df71271f/src/main/java/de/lmu/ifi/dbs/jfeaturelib/features/sift/SiftWrapper.java#L110 since `waitFor()` method accept no parameters instead of two.

**Comment by cute-jumper** [comment]
I found the cause... Java SE 8 does support `waitFor()` with two parameters. So I'm assuming Java 8 is essential for compiling this project?

**Comment by locked-fg** [comment]
Ahh thanks for pointing that out. 
the pom just says
 <maven.compiler.source>1.7</maven.compiler.source>
 <maven.compiler.target>1.7</maven.compiler.target>

This needs to be changed.

**Comment by locked-fg** [comment]
Raised compiler source/target to 1.8 in commit 8f1677705054d900124c75dbbc3aba6725c3b00f . This should fix this issue. Thanks again for reporting

**Comment by cute-jumper** [comment]
Thanks for the quick fix!
